-- Create the core tables used by the website dashboard.
-- Run this in the Supabase SQL editor after creating the project.

create extension if not exists pgcrypto;

create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null default '',
  email text,
  whatsapp text,
  college text,
  semester text,
  branch text,
  technology text,
  languages text,
  preferred_date date,
  interview_format text,
  notes text,
  payment_proof_url text
);

create table if not exists public.finance_records (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  interview_date date,
  candidate text not null default '',
  taken_by text,
  amount numeric(10,2) not null default 0,
  status text not null default 'Pending'
);

create table if not exists public.scheduled_interviews (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  candidate_name text not null default '',
  interviewer_details text not null default '',
  candidate_email text not null default '',
  candidate_phone text not null default '',
  interview_date date not null,
  interview_time text not null default '',
  google_meet_link text not null default '',
  scheduled_by text not null default '',
  status text not null default 'Scheduled',
  details text not null default ''
);

alter table public.scheduled_interviews add column if not exists candidate_phone text not null default '';
alter table public.scheduled_interviews add column if not exists status text not null default 'Scheduled';
alter table public.scheduled_interviews add column if not exists details text not null default '';

alter table public.applications enable row level security;
alter table public.finance_records enable row level security;
alter table public.scheduled_interviews enable row level security;

drop policy if exists "Admin-only access to applications" on public.applications;
drop policy if exists "Admin-only access to finance_records" on public.finance_records;
drop policy if exists "Admins can read applications" on public.applications;
drop policy if exists "Admins can read finance_records" on public.finance_records;
drop policy if exists "Finance admin can write finance_records" on public.finance_records;
drop policy if exists "Admins can read scheduled_interviews" on public.scheduled_interviews;
drop policy if exists "Admins can manage scheduled_interviews" on public.scheduled_interviews;

-- Keep this email list aligned with SUPABASE_CONFIG.adminEmails.
create policy "Admins can read applications"
on public.applications
for select
using (lower(auth.email()) in (
  'sankalp.develop@gmail.com',
  'nextround@admin.com',
  'nextadmin@avinash.com'
));

create policy "Admins can read finance_records"
on public.finance_records
for select
using (lower(auth.email()) in (
  'sankalp.develop@gmail.com',
  'nextround@admin.com',
  'nextadmin@avinash.com'
  -- Add the other admin emails here.
));

create policy "Finance admin can write finance_records"
on public.finance_records
for all
using (lower(auth.email()) = 'sankalp.develop@gmail.com')
with check (lower(auth.email()) = 'sankalp.develop@gmail.com');

create policy "Admins can read scheduled_interviews"
on public.scheduled_interviews
for select
using (lower(auth.email()) in (
  'sankalp.develop@gmail.com',
  'nextround@admin.com',
  'nextadmin@avinash.com'
));

create policy "Admins can manage scheduled_interviews"
on public.scheduled_interviews
for all
using (lower(auth.email()) in (
  'sankalp.develop@gmail.com',
  'nextround@admin.com',
  'nextadmin@avinash.com'
))
with check (lower(auth.email()) in (
  'sankalp.develop@gmail.com',
  'nextround@admin.com',
  'nextadmin@avinash.com'
));

-- Keep this bucket name aligned with the app's upload path.
-- create storage bucket if not exists payment-proofs;

-- Example storage policies for the bucket handle PDF/image uploads from the website.
-- create policy "Allow upload to payment-proofs"
-- on storage.objects for insert
-- with check (bucket_id = 'payment-proofs');
--
-- create policy "Allow read access to payment-proofs"
-- on storage.objects for select
-- using (bucket_id = 'payment-proofs');
