  -- Create the core tables used by the website dashboard.
  -- Run this in the Supabase SQL editor after creating the project.

  create extension if not exists pgcrypto;

  create table if not exists public.applications (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    name text not null default '',
    email text,
    whatsapp text,
    college text,
    semester text,
    branch text,
    technology text,
    languages text,
    session_type text not null default 'mock-interview',
    preferred_date date,
    interview_format text,
    notes text,
    payment_proof_url text,
    source text not null default 'Google Form'
  );

  create table if not exists public.finance_records (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    interview_date date,
    candidate text not null default '',
    taken_by text,
    amount numeric(10,2) not null default 0,
    session_type text not null default 'mock-interview',
    status text not null default 'Pending'
  );

  create table if not exists public.scheduled_interviews (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    candidate_name text not null default '',
    interviewer_details text not null default '',
    candidate_email text not null default '',
    candidate_phone text not null default '',
    interview_date date not null,
    interview_time text not null default '',
    google_meet_link text not null default '',
    scheduled_by text not null default '',
    status text not null default 'Scheduled',
    details text not null default ''
  );

  create table if not exists public.announcements (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    title text not null default '',
    guest_name text not null default '',
    description text not null default '',
    event_date date,
    event_time text not null default '',
    event_end timestamptz not null,
    meet_link text not null default '',
    created_by text not null default ''
  );

  alter table public.scheduled_interviews add column if not exists candidate_phone text not null default '';
  alter table public.scheduled_interviews add column if not exists status text not null default 'Scheduled';
  alter table public.scheduled_interviews add column if not exists details text not null default '';
  alter table public.applications add column if not exists source text not null default 'Google Form';
  alter table public.applications add column if not exists session_type text not null default 'mock-interview';
  alter table public.finance_records add column if not exists session_type text not null default 'mock-interview';
  alter table public.announcements add column if not exists event_end timestamptz;
  alter table public.announcements add column if not exists event_date date;
  alter table public.announcements add column if not exists event_time text not null default '';
  alter table public.announcements add column if not exists meet_link text not null default '';
  alter table public.announcements add column if not exists created_by text not null default '';

  alter table public.applications enable row level security;
  alter table public.finance_records enable row level security;
  alter table public.scheduled_interviews enable row level security;
  alter table public.announcements enable row level security;

  drop policy if exists "Admin-only access to applications" on public.applications;
  drop policy if exists "Admin-only access to finance_records" on public.finance_records;
  drop policy if exists "Admins can read applications" on public.applications;
  drop policy if exists "Anyone can submit applications" on public.applications;
  drop policy if exists "Admins can read finance_records" on public.finance_records;
  drop policy if exists "Anyone can create pending finance records" on public.finance_records;
  drop policy if exists "Finance admin can write finance_records" on public.finance_records;
  drop policy if exists "Admins can read scheduled_interviews" on public.scheduled_interviews;
  drop policy if exists "Admins can manage scheduled_interviews" on public.scheduled_interviews;
  drop policy if exists "Anyone can read active announcements" on public.announcements;
  drop policy if exists "Admins can read announcement history" on public.announcements;
  drop policy if exists "Finance admin can manage announcements" on public.announcements;

  -- Keep this email list aligned with SUPABASE_CONFIG.adminEmails.
  create policy "Admins can read applications"
  on public.applications
  for select
  using (lower(auth.email()) in (
    'sankalp.develop@gmail.com',
    'nextround@admin.com',
    'nextadmin@avinash.com'
  ));

  create policy "Anyone can submit applications"
  on public.applications
  for insert
  with check (true);

  create policy "Admins can read finance_records"
  on public.finance_records
  for select
  using (lower(auth.email()) in (
    'sankalp.develop@gmail.com',
    'nextround@admin.com',
    'nextadmin@avinash.com'
    -- Add the other admin emails here.
  ));

  create policy "Finance admin can write finance_records"
  on public.finance_records
  for all
  using (lower(auth.email()) = 'sankalp.develop@gmail.com')
  with check (lower(auth.email()) = 'sankalp.develop@gmail.com');

  create policy "Anyone can create pending finance records"
  on public.finance_records
  for insert
  with check (status = 'Pending');

  create policy "Admins can read scheduled_interviews"
  on public.scheduled_interviews
  for select
  using (lower(auth.email()) in (
    'sankalp.develop@gmail.com',
    'nextround@admin.com',
    'nextadmin@avinash.com'
  ));

  create policy "Admins can manage scheduled_interviews"
  on public.scheduled_interviews
  for all
  using (lower(auth.email()) in (
    'sankalp.develop@gmail.com',
    'nextround@admin.com',
    'nextadmin@avinash.com'
  ))
  with check (lower(auth.email()) in (
    'sankalp.develop@gmail.com',
    'nextround@admin.com',
    'nextadmin@avinash.com'
  ));

  create policy "Anyone can read active announcements"
  on public.announcements
  for select
  using (event_end > now());

  create policy "Admins can read announcement history"
  on public.announcements
  for select
  using (lower(auth.email()) in (
    'sankalp.develop@gmail.com',
    'nextround@admin.com',
    'nextadmin@avinash.com'
  ));

  create policy "Finance admin can manage announcements"
  on public.announcements
  for all
  using (lower(auth.email()) = 'sankalp.develop@gmail.com')
  with check (lower(auth.email()) = 'sankalp.develop@gmail.com');

  -- Keep this bucket name aligned with the app's upload path.
  insert into storage.buckets (id, name, public)
  values ('payment-proofs', 'payment-proofs', false)
  on conflict (id) do nothing;

  drop policy if exists "Anyone can upload payment proofs" on storage.objects;
  create policy "Anyone can upload payment proofs"
  on storage.objects for insert
  with check (bucket_id = 'payment-proofs');
