// Initial historical financial records provided by NextRound team
window.defaultFinances = [
  { id: 1, date: '20.06.2026', candidate: 'Ramansh Yadav', takenBy: 'Avinash & Sankalp', amount: 79, status: 'Settled' },
  { id: 2, date: '19.07.2026', candidate: 'Sujud Khan', takenBy: 'Did not attended', amount: 79, status: 'Settled' },
  { id: 3, date: '23.07.2026', candidate: 'Pranjal Saxena', takenBy: 'Avinash & Sankalp', amount: 49, status: 'Settled' },
  { id: 4, date: '26.07.2026', candidate: 'Ritul Jain', takenBy: 'Avinash & Sankalp', amount: 49, status: 'Settled' },
  { id: 5, date: '09.08.2026', candidate: 'kaushik vishwakarma', takenBy: 'Avinash , Shashank', amount: 49, status: 'Settled' },
  { id: 6, date: '09.08.2026', candidate: 'Ramansh Yadav', takenBy: 'Ayush', amount: 49, status: 'Settled' },
  { id: 7, date: '14.08.2026', candidate: 'Shreshthi Singh Rajput', takenBy: 'Ayush, Sankalp', amount: 49, status: 'Settled' },
  { id: 8, date: '21.08.2026', candidate: 'Sourabh Patel', takenBy: 'Avinash, Shashank', amount: 49, status: 'Settled' },
  { id: 9, date: '23.08.2026', candidate: 'Om Patel', takenBy: 'Avinash, Sankalp', amount: 49, status: 'Settled' },
  { id: 10, date: '25.08.2026', candidate: 'Nishita Raut', takenBy: 'Avinash', amount: 49, status: 'Settled' },
  { id: 11, date: '30.08.2026', candidate: 'Sourabh Patel', takenBy: 'Ayush, Sankalp', amount: 49, status: 'Settled' },
  { id: 12, date: '31.08.2026', candidate: 'Mahak Rajput', takenBy: 'Sankalp, Sashank', amount: 49, status: 'Settled' },
  { id: 13, date: '01.09.2026', candidate: 'Ajay singh Thakur', takenBy: 'Avinash, Ayush', amount: 49, status: 'Settled' },
  { id: 14, date: '02.09.2026', candidate: 'Namrata Digarse', takenBy: 'Avinash, Sankalp', amount: 49, status: 'Settled' },
  { id: 15, date: '05.09.2026', candidate: 'Ajay singh Thakur', takenBy: 'Sankalp', amount: 79, status: 'Settled' },
  { id: 16, date: '05.09.2026', candidate: 'Shreshthi Singh Rajput', takenBy: 'Avinash', amount: 79, status: 'Settled' },
  { id: 17, date: '05.09.2026', candidate: 'Sourabh Patel', takenBy: 'Sashank', amount: 49, status: 'Settled' },
  { id: 18, date: '06.09.2026', candidate: 'Om Patel', takenBy: 'Ayush, Avinash', amount: 49, status: 'Settled' },
  { id: 19, date: '06.09.2026', candidate: 'Ishan', takenBy: 'Avinash', amount: 79, status: 'Settled' },
  { id: 20, date: '06.09.2026', candidate: 'Mahak Rajput', takenBy: 'Ayush, Avinash', amount: 79, status: 'Settled' },
  { id: 21, date: '07.09.2026', candidate: 'DivyaPraksh Dwivedi', takenBy: 'Avinash', amount: 79, status: 'Settled' },
  { id: 22, date: '13.09.2026', candidate: 'kaushik vishwakarma', takenBy: 'Avinash', amount: 79, status: 'Settled' },
  { id: 23, date: '14.09.2026', candidate: 'Abhinav Jain', takenBy: 'Avinash', amount: 79, status: 'Settled' },
  { id: 24, date: '15.09.2026', candidate: 'Harsh Thakur', takenBy: 'Sankalp', amount: 79, status: 'Settled' },
  { id: 25, date: '16.09.2026', candidate: 'Om Patel', takenBy: 'Ayush', amount: 79, status: 'Settled' },
  { id: 26, date: '19.09.2026', candidate: 'Shreya Pathak', takenBy: 'Avinash', amount: 79, status: 'Settled' },
  { id: 27, date: '20.09.2026', candidate: 'Aarya Gupta', takenBy: 'Sankalp', amount: 79, status: 'Pending' }
];
